export const userTypes = {
  FETCHING_USER: "FETCHING_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR",
  SIGNIN_USER_SUCCESS: "SIGNIN_USER_SUCCESS",
  SIGNIN_USER_ERROR: "SIGNIN_USER_ERROR",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_ERROR: "SIGNUP_USER_ERROR",
  SIGNOUT_USER_SUCCESS: "SIGNOUT_USER_SUCCESS",
  SIGNOUT_USER_ERROR: "SIGNOUT_USER_ERROR",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_ERROR: "DELETE_USER_ERROR"
};
